/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { Sample, SampleInterface } from '../Sample'

const _abi = [{}]

export class Sample__factory {
  static readonly abi = _abi
  static createInterface(): SampleInterface {
    return new utils.Interface(_abi) as SampleInterface
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Sample {
    return new Contract(address, _abi, signerOrProvider) as Sample
  }
}
